project_id = "slcuaijctwvmumgtpxgv"

[functions.create-pix]
verify_jwt = false

[functions.hygros-webhook]
verify_jwt = false

[functions.save-card-lead]
verify_jwt = false

[functions.tiktok-events-api]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.send-trackly-webhook]
verify_jwt = false

[functions.product-chat]
verify_jwt = false
